# Codecov configuration to make it a bit less noisy
coverage:
  status:
    patch:
      default:
        threshold: 5%
    project:
      default:
        threshold: 50%
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null
ignore:
  - "*/tests/*"
