# readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"

python:
  install:
    - method: pip
      path: .

conda:
  environment: docs/requirements.yaml

# Configuration for Sphinx documentation
sphinx:
   configuration: docs/conf.py
   fail_on_warning: false
